name: Mobile Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Install dependencies
      run: npm install
    
    - name: Start Appium Server
      run: |
        npm install -g appium
        appium &
        
    - name: Run tests
      run: npm test
      
    - name: Generate Allure Report
      if: always()
      run: npm run report
      
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report/
        
    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: screenshots/